### ISSUE TITLE
BMW hat wohl die API komplett geändert

### ISSUE THREAD

**Issue by JVinki** [Wolbolar/IPSymconBMWConnectedDrive#23]
BMW hat wohl die API komplett geändert. 
Ist hier ein Update geplant?

MfG
J.Vinkelau

**Comment by dg3fbl** [comment]
Das würde mich auch interessieren, hatte mir gerade das Modul installiert, aber da kommt nichts sinnvolles....

Grüße
Jochen

**Comment by IPSAttain** [comment]
Das Modul wird von demel weiter gepflegt.
Bitte da entlang ->: https://github.com/demel42/IPSymconBMWConnectedDrive
